[profile.default]
src = "src"
out = "out"
libs = ["lib"]
verbosity = 3
solc = '0.8.23'
optimizer = true
optimizer_runs = 20_000
remappings = ['@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/']
ffi = true

[fuzz]
runs = 10

# https://book.getfoundry.sh/reference/config/formatter
[fmt]
bracket_spacing = true


################################################################
#                          CI profile                          #
################################################################

[profile.ci]
solc = '0.8.23'
via_ir = true
optimizer = true
optimizer_runs = 1_000_000
ffi = true

[profile.ci.fuzz]
runs = 2048