[package]
name = "boilerplate-rs"
description = "Binary crate for boilerplate-rs"
authors = ["clabby"]
version = "0.1.0"
edition = "2021"

[dependencies]
# External
clap = { version = "4.1.13", features = ["derive"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
anyhow = "1.0.70"

# Local
zero-kompressor = { path = "../crates/zero-kompressor" }

[[bin]]
name = "diff"
path = "src/diff.rs"
