[package]
name = "zero-kompressor"
description = "A library for encoding and decoding ZeroKompressed bytes."
authors = ["clabby"]
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.70"
ethers = "2.0.1"
tracing = "0.1.37"
