name: Test CI
on:
  push:
    paths:
      - rust/**
      - js/**
      - src/**
      - test/**

env:
  FOUNDRY_PROFILE: ci

jobs:
  run-ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - uses: Swatinem/rust-cache@v2.7.2
        with:
          cache-on-failure: true

      - name: Build Differential Tests
        working-directory: ./rust
        run: cargo build --all --release
        id: build-rust

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          # cache: "pnpm"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
  
      - name: Install deps (Node.js)
        working-directory: ./js
        run: pnpm install

      - name: Run tests (Node.js)
        working-directory: ./js
        run: pnpm test

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install deps (Foundry)
        run: forge install

      - name: Run tests (Foundry)
        run: forge test

